import { ACCOUNT_STATUS, MESSAGES, ROLES } from "@/constants/app.constants";
import { EmailService } from "@/services/email.service";
import { PasswordGeneratorService } from "@/services/password-generator.service";
import {
  BadRequestException,
  ConflictException,
  NotFoundException,
} from "@/utils/app-error.utils";
import { UserService } from "../user/user.service";
import type { UserResponse } from "../user/user.type";
import type { IGolfClub, IGolfClubMember } from "./golf-club.interface";
import {
  GolfClubMemberRepository,
  GolfClubRepository,
} from "./golf-club.repository";
import type {
  AddClubMemberPayload,
  AssignClubManagerPayload,
  CreateGolfClubPayload,
  GolfClubMemberResponse,
  GolfClubResponse,
} from "./golf-club.type";

export class GolfClubService {
  private golfClubRepository: GolfClubRepository;
  private golfClubMemberRepository: GolfClubMemberRepository;
  private userService: UserService;
  private emailService: EmailService;
  private passwordGeneratorService: PasswordGeneratorService;

  constructor() {
    this.golfClubRepository = new GolfClubRepository();
    this.golfClubMemberRepository = new GolfClubMemberRepository();
    this.userService = new UserService();
    this.emailService = new EmailService();
    this.passwordGeneratorService = new PasswordGeneratorService();
  }

  async createGolfClub(
    payload: CreateGolfClubPayload,
    adminEmail: string
  ): Promise<GolfClubResponse> {
    const clubName = payload.clubName.trim();
    const generatedPassword = this.passwordGeneratorService.generate();

    const clubUser = await this.userService.createUser({
      email: payload.email,
      password: generatedPassword,
      fullName: clubName,
      role: ROLES.GOLF_CLUB,
      emailVerified: true,
      accountStatus: ACCOUNT_STATUS.ACTIVE,
      address: "",
      passwordAutoGenerated: true,
    });

    const club = await this.golfClubRepository.create({
      name: clubName,
      clubUserId: clubUser._id,
      managerUserId: null,
    });

    await this.emailService.sendGolfClubCredentials({
      to: adminEmail,
      recipientRole: "Admin",
      clubName,
      clubEmail: clubUser.email,
      clubPassword: generatedPassword,
    });

    return this.toGolfClubResponse(club, clubUser.email);
  }

  async listGolfers(): Promise<UserResponse[]> {
    const golfers = await this.userService.getUsersByRole(ROLES.GOLFER);
    return golfers.map((golfer) => this.userService.toUserResponse(golfer));
  }

  async assignManager(
    payload: AssignClubManagerPayload
  ): Promise<GolfClubResponse> {
    const club = await this.golfClubRepository.findById(payload.clubId);
    if (!club) {
      throw new NotFoundException("Golf club not found.");
    }

    const golfer = await this.userService.getById(payload.golferUserId);
    if (!golfer) {
      throw new NotFoundException(MESSAGES.USER.USER_NOT_FOUND);
    }

    if (golfer.role !== ROLES.GOLFER) {
      throw new BadRequestException("Selected user is not a golfer.");
    }

    const updatedClub = await this.golfClubRepository.updateById(
      payload.clubId,
      { managerUserId: golfer._id }
    );

    if (!updatedClub) {
      throw new NotFoundException("Golf club not found.");
    }

    const clubUser = await this.userService.getById(
      club.clubUserId.toString()
    );
    if (!clubUser) {
      throw new NotFoundException("Golf club login not found.");
    }

    const generatedPassword = this.passwordGeneratorService.generate();
    await this.userService.updateAutoGeneratedPassword(
      clubUser._id.toString(),
      generatedPassword
    );

    await this.emailService.sendGolfClubCredentials({
      to: golfer.email,
      recipientName: golfer.fullName,
      recipientRole: "Club Manager",
      clubName: updatedClub.name,
      clubEmail: clubUser.email,
      clubPassword: generatedPassword,
    });

    return this.toGolfClubResponse(updatedClub, clubUser.email);
  }

  async addMember(
    payload: AddClubMemberPayload
  ): Promise<GolfClubMemberResponse> {
    const club = await this.golfClubRepository.findById(payload.clubId);
    if (!club) {
      throw new NotFoundException("Golf club not found.");
    }

    const golfer = await this.userService.getById(payload.golferUserId);
    if (!golfer) {
      throw new NotFoundException(MESSAGES.USER.USER_NOT_FOUND);
    }

    if (golfer.role !== ROLES.GOLFER) {
      throw new BadRequestException("Selected user is not a golfer.");
    }

    const existingMember =
      await this.golfClubMemberRepository.findByClubAndGolfer(
        payload.clubId,
        payload.golferUserId
      );
    if (existingMember) {
      throw new ConflictException("Golfer is already a member of this club.");
    }

    const member = await this.golfClubMemberRepository.create({
      clubId: payload.clubId,
      golferUserId: payload.golferUserId,
    });

    return this.toGolfClubMemberResponse(member);
  }

  private toGolfClubResponse(
    club: IGolfClub,
    clubEmail: string
  ): GolfClubResponse {
    return {
      _id: club._id.toString(),
      name: club.name,
      clubUserId: club.clubUserId.toString(),
      clubEmail,
      managerUserId: club.managerUserId?.toString() ?? null,
      createdAt: club.createdAt,
      updatedAt: club.updatedAt,
    };
  }

  private toGolfClubMemberResponse(
    member: IGolfClubMember
  ): GolfClubMemberResponse {
    return {
      _id: member._id.toString(),
      clubId: member.clubId.toString(),
      golferUserId: member.golferUserId.toString(),
      createdAt: member.createdAt,
      updatedAt: member.updatedAt,
    };
  }
}
