// file: src/modules/user/user.type.ts

import type { ACCOUNT_STATUS, ROLES } from "@/constants/app.constants";

export type UserResponse = {
  _id: string;
  email: string;
  fullName: string;
  userName?: string;
  phoneNumber: string;
  address: string;
  bio?: string;
  role: (typeof ROLES)[keyof typeof ROLES];
  accountStatus: (typeof ACCOUNT_STATUS)[keyof typeof ACCOUNT_STATUS];
  emailVerified: boolean;
  lastLoginAt?: Date;
  profileImage?: string | null;
  coverImage?: string | null;
  profileImageUrl?: string | null;
  coverImageUrl?: string | null;
  followerCount?: number;
  followingCount?: number;

  createdAt: Date;
  updatedAt: Date;
};

export type UserCreatePayload = {
  email?: string;
  password?: string;
  fullName: string;
  userName?: string;
  phoneNumber?: string;
  address?: string;
  bio?: string;
  role: (typeof ROLES)[keyof typeof ROLES];
  emailVerified?: boolean;
  accountStatus?: (typeof ACCOUNT_STATUS)[keyof typeof ACCOUNT_STATUS];
  passwordAutoGenerated?: boolean;
};

export type UpdateUserPayload = {
  fullName?: string;
  phoneNumber?: string;
  address?: string;
  bio?: string;
  userName?: string;
  profileImageUrl?: string;
  coverImageUrl?: string;
};

export type ChangePasswordPayload = {
  currentPassword: string;
  newPassword: string;
};

export type JWTPayload = {
  userId: string;
  email: string;
  role: string;
  accountStatus: string;
  emailVerified?: boolean;
  iat?: number;
  exp?: number;
};
